version: 2

jobs:
  build:
    working_directory: /ci
    docker:
      - image: docker:18.06.0-ce-git
    environment:
      DOCKER_IMAGE: cheky
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            export DOCKER_IMAGE_TAG=$(cat VERSION)
            docker build --no-cache -t "${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}" .
            docker images
workflows:
  version: 2
  default:
    jobs:
      - build:
          context: sk-docker-hub
