version: 2

jobs:
  build:
    working_directory: /ci
    docker:
      - image: docker:18.06.0-ce-git
    environment:
      DOCKER_IMAGE: cheky
      DOCKER_HUB_NAMESPACE: skurtzemann
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            export DOCKER_IMAGE_TAG=$(cat VERSION)
            docker build --no-cache -t "${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}" .
            docker images
      - run:
          name: Push image
          command: |
            docker login -u ${DOCKER_HUB_LOGIN} -p ${DOCKER_HUB_PASS}
            docker tag ${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG} ${DOCKER_HUB_NAMESPACE}/${DOCKER_IMAGE}:${CIRCLE_BRANCH}
            docker push ${DOCKER_HUB_NAMESPACE}/${DOCKER_IMAGE}:${CIRCLE_BRANCH}

workflows:
  version: 2
  default:
    jobs:
      - build:
          context: sk-docker-hub
